# configs/settings.yaml

# OpenAI API configuration
openai:
  api_key: "YOUR_OPENAI_API_KEY"  # override with .env for security
  model: "gpt-4"  # or "gpt-3.5-turbo"
  temperature: 0.2
  max_tokens: 1024

# Pinecone configuration
pinecone:
  api_key: "YOUR_PINECONE_API_KEY"
  environment: "us-west1-gcp"
  index_name: "chatvet-index"

# Embedding configuration
embedding:
  model: "text-embedding-ada-002"
  max_batch_size: 100

# Chatbot behavior
chatbot:
  use_symptom_checker: true
  symptom_match_threshold: 0.5

# Application limits
limits:
  max_question_length: 512
  max_chat_history: 20

# UI flags
ui:
  theme: "light"
  enable_custom_css: true
  title: "ChatVet - AI Health Assistant for Pets"

# Developer mode
dev:
  debug_mode: false
  enable_logs: true
